// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID      int64              `json:"account_id"`
	DocumentNumber string             `json:"document_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OperationType struct {
	OperationTypeID int32  `json:"operation_type_id"`
	Description     string `json:"description"`
}

type Transaction struct {
	TransactionID   int64              `json:"transaction_id"`
	AccountID       int64              `json:"account_id"`
	OperationTypeID int64              `json:"operation_type_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
