// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, documentNumber string) (Account, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetAccountByID(ctx context.Context, accountID int64) (Account, error)
	GetTransaction(ctx context.Context, transactionID int64) (Transaction, error)
	ListTransactionsByAccount(ctx context.Context, accountID int64) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
