// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, operation_type_id, amount)
VALUES ($1, $2, $3)
    RETURNING transaction_id, account_id, operation_type_id, amount, created_at
`

type CreateTransactionParams struct {
	AccountID       int64          `json:"account_id"`
	OperationTypeID int64          `json:"operation_type_id"`
	Amount          pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.AccountID, arg.OperationTypeID, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.AccountID,
		&i.OperationTypeID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT transaction_id, account_id, operation_type_id, amount, created_at FROM transactions
WHERE transaction_id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, transactionID int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.AccountID,
		&i.OperationTypeID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT transaction_id, account_id, operation_type_id, amount, created_at FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TransactionID,
			&i.AccountID,
			&i.OperationTypeID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
